# Site settings
title: naxmefy | developer
email: naxmefy@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  naxmefy | developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://naxmefy.github.io" # "http://www.nax.me" # the base hostname & protocol for your site
twitter_username: naxmefy
github_username:  naxmefy

# Build settings
markdown: kramdown
