# Site settings
title: Naxmeify <Nax aka Matt>
email: matt@nax.me
description: > # this means to ignore newlines until "baseurl:"
  MRW Neundorf aka Matt aka Nax. Web, Mobile, Desktop Developer. Business, Games and much more.
  Welcome on my Homepage. I am going to blog about developing and much more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nax.me" # the base hostname & protocol for your site
twitter_username: Naxmeify
github_username:  Naxmeify

# Build settings
markdown: kramdown
